services:
  flask_app-test:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: flask-test
    restart: always
    depends_on:
      - db-test
    environment:
      POSTGRESQL_USER: ${POSTGRESQL_USER}
      POSTGRESQL_PASSWORD: ${POSTGRESQL_PASSWORD}
      POSTGRESQL_DB: ${POSTGRESQL_DATABASE}
      DATABASE_HOST: ${DATABASE_HOST_TEST}
      POSTGRESQL_DATABASE_PORT: 5432
    ports:
      - "5000:5000"
    networks:
      - mynetwork
    env_file:
      - .env
    command: [ "/bin/sh", "-c", "/wait-for-postgres.sh db-test && gunicorn -w 4 --timeout 120 --bind 0.0.0.0:5000 main:app" ]

  db-test:
    image: postgres:15
    platform: linux/amd64
    container_name: postgresql_db-test
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRESQL_DATABASE}
      POSTGRES_USER: ${POSTGRESQL_USER}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - mynetwork
    volumes:
      - postgresql_data:/var/lib/postgresql/data

networks:
  mynetwork:
    driver: bridge

volumes:
  postgresql_data:
