version: "3.9"

services:
  app:
    build: .
    ports:
      - "5000:5000"
    container_name: my_python_app
    volumes:
      - .:/app
    working_dir: /app
    command: gunicorn -w 4 -b 0.0.0.0:5000 main:app
