name: AWS Deploy

on:
  workflow_run:
    workflows: ["Docker Deploy"]
    types:
      - completed

permissions:
  contents: read

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    environment: deploy
    env:
      SSH_KEY: ${{ secrets.SSH_KEY }}
      AWS_MACHINE_USER: ${{ secrets.AWS_MACHINE_USER }}
      AWS_MACHINE_HOST: ${{ secrets.AWS_MACHINE_HOST }}

    steps:

      - uses: actions/checkout@v3

      - name: Verify SSH Key
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p 22 $AWS_MACHINE_HOST >> ~/.ssh/known_hosts

      - name: SSH Remote Machine
        run: |
          touch key.pem
          echo "${SSH_KEY}" > key.pem
          chmod 600 key.pem
          ssh -i "key.pem" $AWS_MACHINE_USER@$AWS_MACHINE_HOST

      - name: Stop Service
        run: |
          cd app
          docker-compose down
      - name: Run Service
        run : docker-compose up --build -d

      - name: Health Check
        run: curl http://localhost:5000
